/**
 * NEW DOMAIN MODEL FOR SCHEDULING (Motion-style Architecture)
 *
 * This file defines the core entities for the scheduling system.
 * Each entity has a clear purpose and constraints.
 */

// ============================================================================
// 1. EXTERNAL CALENDAR EVENTS (Hard Constraints - Not Movable)
// ============================================================================

/**
 * Events from external calendars (Google, Outlook, etc.)
 * These are READ-ONLY and cannot be moved by the scheduler.
 * They serve as fixed constraints that the scheduler must work around.
 */
export interface ExternalCalendarEvent {
  id: string;
  provider: 'google' | 'outlook' | 'ical';
  providerEventId: string; // Original ID from the provider

  // Event details
  title: string;
  description?: string;
  start: Date;
  end: Date;
  isAllDay: boolean;
  location?: string;

  // Meeting/conference details
  conferenceData?: {
    type: 'google_meet' | 'zoom' | 'teams' | 'other';
    uri?: string;
    hangoutLink?: string;
  };

  // Attendees
  attendees?: Array<{
    email: string;
    name?: string;
    responseStatus: 'accepted' | 'declined' | 'tentative' | 'needsAction';
    avatar?: string;
  }>;

  organizer?: {
    email: string;
    name?: string;
    isSelf: boolean;
  };

  // Metadata
  recurrence?: string;
  source: 'external'; // Always external
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================================
// 2. MEETINGS (Hard Constraints - Not Movable)
// ============================================================================

/**
 * Scheduled meetings that are fixed and cannot be moved.
 * These can be created manually or synced from external calendars.
 * The scheduler treats them as hard constraints.
 */
export interface Meeting {
  id: string;
  userId: string;

  // Meeting details
  title: string;
  description?: string;
  start: Date;
  end: Date;
  isAllDay: boolean;
  location?: string;

  // Meeting type
  meetingType: 'in_person' | 'virtual' | 'hybrid';
  meetingUrl?: string;

  // Participants
  attendees: Array<{
    email: string;
    name?: string;
    responseStatus: 'accepted' | 'declined' | 'tentative' | 'needsAction';
    avatar?: string;
  }>;

  // Constraints
  isRecurring: boolean;
  recurrenceRule?: string;

  // Metadata
  source: 'manual' | 'external' | 'synced';
  externalEventId?: string; // Reference to ExternalCalendarEvent if synced
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================================
// 3. TASKS (Flexible Work - Movable)
// ============================================================================

/**
 * Executable work that can be scheduled and moved by the scheduler.
 * Tasks have priorities, deadlines, and can be split into blocks.
 */
export interface Task {
  id: string;
  userId: string;

  // Task details
  title: string;
  description?: string;

  // Priority and urgency
  priority: 'critical' | 'high' | 'medium' | 'low';
  priorityValue: number; // 4 = critical, 3 = high, 2 = medium, 1 = low
  urgency: 'immediate' | 'today' | 'this_week' | 'this_month' | 'flexible';

  // Time constraints
  deadline?: Date; // Soft deadline (can be moved if necessary)
  hardDeadline?: Date; // Hard deadline (cannot be moved past this)
  estimatedDuration: number; // In minutes

  // Task state
  status:
    | 'backlog'
    | 'planned'
    | 'scheduled'
    | 'in_progress'
    | 'completed'
    | 'cancelled';

  // Dependencies
  dependsOnTaskIds: string[]; // Tasks that must complete before this one
  blocksTaskIds: string[]; // Tasks that cannot start until this one completes

  // Metadata
  category?: string;
  tags: string[];
  color?: string;
  source: 'manual' | 'ai_suggested';
  createdAt: Date;
  updatedAt: Date;
  completedAt?: Date;
}

// ============================================================================
// 4. WORK BLOCKS (Generated Time Blocks)
// ============================================================================

/**
 * Time blocks generated by the scheduler for specific tasks.
 * These are the actual time allocations on the calendar.
 */
export interface WorkBlock {
  id: string;
  userId: string;
  taskId?: string; // Reference to the Task this block belongs to (optional for breaks/buffers)

  // Time allocation
  start: Date;
  end: Date;
  duration: number; // In minutes

  // Block type
  blockType: 'focus' | 'break' | 'buffer' | 'transition';

  // Constraints
  isGenerated: boolean; // If true, generated by scheduler; if false, manually placed

  // Scheduling metadata
  schedulingScore?: number; // How well this block fits the task's preferences
  schedulingReason?: string; // Why the scheduler placed it here

  // Metadata
  createdAt: Date;
  updatedAt: Date;
}

// ============================================================================
// 5. SCHEDULING CONSTRAINTS (User Preferences)
// ============================================================================

/**
 * User-level scheduling constraints that the scheduler must respect.
 */
export interface SchedulingConstraints {
  userId: string;

  // Working hours
  workingDays: Array<'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun'>;
  workingHours: {
    start: string; // "09:00"
    end: string; // "17:00"
  };

  // Break preferences
  breakDuration: number; // In minutes
  breakInterval: number; // Maximum work duration before forced break (in minutes)

  // Focus preferences
  preferredFocusBlockDuration: number; // Ideal focus block length (in minutes)
  minFocusBlockDuration: number; // Minimum acceptable focus block (in minutes)
  maxFocusBlockDuration: number; // Maximum acceptable focus block (in minutes)

  // Scheduling strategy
  schedulingStrategy: 'earliest_deadline' | 'priority_first' | 'balanced';
  allowSameDaySplitting: boolean; // Can tasks be split across multiple days?
  allowOvertime: boolean; // Can scheduler schedule beyond working hours?

  // Golden window (optimal working time)
  goldenWindow?: {
    start: string; // "09:00"
    end: string; // "11:00"
  };

  // Metadata
  updatedAt: Date;
}

// ============================================================================
// 6. SCHEDULING RESULT (Output from Scheduler)
// ============================================================================

/**
 * Result of a scheduling operation.
 */
export interface SchedulingResult {
  userId: string;
  scheduledAt: Date;

  // What was scheduled
  scheduledTasks: Array<{
    taskId: string;
    workBlocks: WorkBlock[];
    status: 'scheduled' | 'partially_scheduled' | 'could_not_schedule';
    reason?: string;
  }>;

  // What couldn't be scheduled
  unscheduledTasks: Array<{
    taskId: string;
    reason:
      | 'no_available_slots'
      | 'deadline_passed'
      | 'constraints_conflict'
      | 'insufficient_time';
    suggestedAction?: string;
  }>;

  // Conflicts detected
  conflicts: Array<{
    type: 'overlap' | 'deadline_conflict' | 'dependency_conflict';
    description: string;
    affectedTaskIds: string[];
  }>;

  // Statistics
  totalTasksScheduled: number;
  totalWorkBlocksCreated: number;
  totalScheduledMinutes: number;
  schedulingEfficiency: number; // 0-1, how well it utilized available time
}
